# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11e286954ac59d831995604ce8040a9b0d2283d0602e97f5528f6c0151d0e9fedac8d057f3214215ee770672f543c29fb2b3926fb44bcabf730ef48d67ddf012

test:
  secret_key_base: 1d9377f30a89e691e305e9a18787abcc92cb2e9ac6fefc64be454fc406d25d94c62b718dd5ea410539e171dfd3acec7718176f06b5ce391752aab2a58986657e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
